"""Refactored base model

Revision ID: 349c56ce3ede
Revises: 0f672e29d2c8
Create Date: 2026-06-28 21:29:12.081704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349c56ce3ede'
down_revision: Union[str, Sequence[str], None] = '0f672e29d2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    # ### end Alembic commands ###
